### ISSUE TITLE
将前半部分示例的主题改进

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/java_in_hours_chn#2]
源自https://github.com/program-in-chinese/java_in_hours_chn/issues/1#issuecomment-339573872:

最好和后半部分的主题(人)接近

**Comment by nobodxbodon** [comment]
@jeffreybaoshenlee 恐怕没有达到预期效果, 只对示例代码作了小改. 尤其是那个[投资回报](https://github.com/program-in-chinese/java_in_hours_chn#%E4%BA%94-%E5%8F%98%E9%87%8F-%E5%9C%A8%E7%A8%8B%E5%BA%8F%E4%B8%AD%E4%BF%9D%E5%AD%98%E4%BF%AE%E6%94%B9%E4%BF%A1%E6%81%AF)的例子, 后面还用来介绍[控制流](https://github.com/program-in-chinese/java_in_hours_chn#%E5%85%AB-%E7%9B%B4%E5%88%B0%E4%B8%80%E7%9B%B4), 暂时没想到什么合适的替代. 用身高体重之类好像有些敏感.

如果重新构思的话, 也许能有更统一的主题, 不过估计要大改了.

**Comment by jeffreybaoshenlee** [comment]
@nobodxbodon 嗯，不急，慢慢考慮。

我想，或許可以構造一套個人事務（或者家庭事務、團隊事務）管理系統，把這些例子給整合起來，但具體怎麼實行，我還沒想好，只是暫時說一下，哈哈。

**Comment by nobodxbodon** [comment]
当初设想的目标读者是零经验的编程新手，所以尽量把示例缩减，在保证可演示（运行）和趣味性的前提下用尽量少的代码覆盖最基本的知识点。
如果做成管理系统的话（CRUD？），代码量可能会大一些，而且可能会更接近工程。
之前还用中文代码写了一点Spring Boot的[演示](https://github.com/program-in-chinese/jinxiaocun/blob/master/src/main/java/com/example/%E5%8D%95%E4%BD%8D%E6%8E%A7%E5%88%B6.java)，现在考虑是不是写一些框架相关的短教程（当然也是尽量用中文代码示例）

**Comment by jeffreybaoshenlee** [comment]
嗯，《Thinking in Java》（《Java 編程思想》）那本書的例子，也是這樣安排的，儘量簡潔、自成一體，以便於單獨演示。如果做成工程的話，新手演示和理解起來，或許不太方便。

補記：然後，我又想到，以後可以把教程分成幾個系列，一個是專門針對新手的（就是本教程），還有一個是中階或高階一些的教程，可以安排幾個工程進去。

**Comment by nobodxbodon** [comment]
很同意教程分阶。
关于下一步的教程的选择，个人的感觉是，初阶教程编写费工相对较小，而目标读者需求最大。而编程语言之外，针对一些流行开发框架编写初阶教程也许更接近实用，同时也检验这些框架对中文代码的友好程度。不知你有什么看法？

BTW之前刚想到一个例子可能可以作为理财例子的替代，虽然还是不大自然。 就是小孩识字量，比如2岁的时候认识两个字，每个月增长10%，到多大能认识常用的三千字。

**Comment by nobodxbodon** [comment]
@jeffreybaoshenlee 刚改了理财例子. 另外可能会新开一个Scala的入门教程/学习笔记, 主要因为工作需要. 欢迎建议意见.

**Comment by jeffreybaoshenlee** [comment]
用框架來檢驗中文代碼的友好程度，這個想法很好。大期待～

**Comment by jeffreybaoshenlee** [comment]
Scala，好啊，我剛剛接觸這門語言，最近打算看看這方面的教程。

**Comment by nobodxbodon** [comment]
好的. 已将之前的提议添加在https://github.com/program-in-chinese/overview/issues/5#issuecomment-319502367
此issue好像可以暂告一段落.
多谢!
